= Abstract
In dieser Arbeit befassten wir uns mit der Relevanz der Story in Video&#173;spielen.
Auf die Idee sind wir gekommen, weil wir beide seit Kindertagen Gamer sind.
Wir stellten die These auf, dass die Story, also die Handlung, von Games immer mehr in den Hintergrund rückt und die Online Funktion wichtiger wird.
Wir dachten uns, dass sowohl die Hersteller der Video&#173;spiele und vor allem die jüngeren Gamer dies bevorzugen.
Um diese These zu untersuchen, haben wir eine Umfrage gemacht. An dieser Umfrage nahmen 120 Leute Teil, die alle in verschiedenen Alterskategorien eingeordnet wurden.
Ebenfalls wollten wir mit dieser Arbeit denen, die sich nicht so mit der Thematik Video&#173;spiele auskennen, einen kleinen Einblick verschafften, indem wir ein wenig die Ge&#173;schich&#173;te von Gaming erläuterten und ein paar Genres erklärten.
Die Ergebnisse der Umfrage konnten die These nicht unterstützen, da ziemlich schnell klar wurde, dass die Befragten  immer noch eine durchdachte Handlung wollen und momentan damit zufrieden sind, wie es von den Herstellern gehandhabt wird.
Wir waren von diesen Ergebnissen überrascht, da die meisten Spieler immer noch die Einzelspieler-Kampagnen gegenüber dem Onlinemodus bevorzugen.
Somit kann vermutet werden, dass die Relevanz der Story in Games seit dem Millennium nicht gesunken ist.
