= Auswertung der Umfrage

== Einführung

Unsere Fragestellung lautet: "Hat sich die Relevanz der Story-Line der Games in den letzten 20 Jahren verändert?"
Wir haben versucht dieser Frage in unserer Umfrage nachzugehen.
Um ein besseres Bild über die Befragten zu bekommen, waren Fragen nach dem Alter, seit wann und wie oft sie Videospiele spielen.
Die Leitfrage untersuchten wir mit Fragen nach dem Spiel mit der besten Story, wie wichtig Story in einem Videospiel ist und natürlich wie zufrieden sie mit der Story in heutigen Games sind.
Wir haben die Umfrage in verschiedene Gaming-Foren gestellt, Auf Twitter und Facebook verbreitet und es an Freunde und Familie geschickt.
Insgesamt haben über 100 Personen an der Umfrage Teilgenommen.

== Kritik der Umfrage

Uns ist bewusst, dass diese Umfrage nicht Representativ ist, weil nur wenige Teilnehemer, die diese Umfrage auch selber beantworten (Selbstselektion) wollten teilnahmen.
Die Selbstselektion ist unserer Meinung nach kein Problem, weil sich die Umfrage an Gamer wendet und darum auch nur Leute mit affienität zum Spielen teilgenommen haben.
Um die Qualität der Ausagen zu Quantifizieren haben wir den Standartfehler berrechnet, der Standartfehler ist zwei mal die Standerabweichung die wir wie folgt berechnen: Wir nehmen an das die Antworten aus der Umfrage gleichartig und unabhängig voneinander sind und deshalb Binominal verteilt sind.
Den Standartfehler kann man dann mit der Formel blavblabla ausrechnen.
Dabei ist P der gemessene Parameter und n die grösse der Population.
Die Standartabweichung verändert sich mit der grösse P.
Für die verscheidenen Fragen in unserer Umfrage schwankt die Standartabweichung zwichen 0.029 (für grosse P) und 0.045 (für P nahe 0.5).
Der Standartfehler ist also zwischen 0.04 und 0.09.
Der einfachheit halber rechenen wir durchgehend mit einem Fehler von ≈ 0.075.

== Analyse der Ergebnisse

An unserer Umfrage haben 85% männliche Personen und 15% Weibliche Teilgenommen.
Fast 80% der Teilnehemer waren über 23 Jahre alt davon 45% soga über 30 Jahre alt.
Wie man sieht ist der Hauptteil unseres Teilnehmerfeldes eher älter, was für uns gut ist, weil wir aus der Umfrage eine einschätzung für das Gamen in den letzten 20 Jahren erhalten.
Etwa 85% der Befragten haben bereits als Kinder unter 16 Jahren begonnen Videospiele zu spielen und ca. die Hälfte spielt heute noch täglich Videospiele.
20% spielen heute nicht mehr regelmässig Videospiele.
Für über 80% der Teilnehmer ist die Storyline in einem Videospiel wichtig.
30% davon sehen die Storyline als wichtigstes Element an und für über 50% ist die Story wichtig jedoch nicht das wichtigste.
Die nächste Frage ist auch sehr spannend, wir fragten was in einem Spiel wichtiger sei, Story oder Gameplay.
Etwa doppelt so viele Personen finden Gamplay wichtiger als Story.
Bei der Frage wie diese Personen die Story erleben haben wir Herausgefunden das etwa 80% der befragten die Cutscenes und die Sprachausgabe ansehen.
Da die Frage mehere Antwoertsmöglichkeiten hatte, haben wir zudem erfahren das 50% zudem nach Storyelementen wie Tagebücher oder collecctabels suchen.
Nur etwa 10% ist eher uninteresiert an der Story eines Spiels.
Nun kommt eine der Wichtigsten Fragen der Umfrage, wir fragten:"Bist du mit der Storyline in Spielen seit 2012 zufreiden."
Die Antwoert hat uns sehr überascht.
Die meisten sagten das sie im allgemeinen zufrieden sind mit Storys in neuen Videospielen.
Klar gab es auch antworten die sagten das sie nicht zufrieden sind unsogar eine die ganz unzufrieden ist.
Was auch nich interessant ist, dass niemand die 10 angekreuzt hat, also keiner der Befragten ist zu 100% zufrieden, es hat potential für verbesserung.
Ca. ein Drittel der Befragten erlebt eine Story leiber alleine in einem Singleplayer Spiel, wobei der rest die Story auch gerne im Multiplayer mit Mitspielern erlebt.
Was braucht eine gute Story, nun fast alle der Befragten waren sich einig das gute Charakter und Spannung sehr wichtige Elemente eines Videospiels sind.
Emotionen waren auch hoch mit dabei.
wir leisen den Teilnehemer die wahl noch eigene antworten zu dieser Frage zu schreiben und bekammen sehr viele einzelne Antwoerten.
Für eine Person war die Immersion sehr wichtig, also er will sich im Spiel verlieren und ganz in die Welt abtauchen.
Eine sehr spannende antwoer war, das sich eine Person wünscht, dass der Spieler Ethisch Fragen beantworten muss.
Nun zum schluss fragten wir welches Spiel die beste Story ihrer meinung nach habe.
Wir bekammen entliche Antworten und sehen einige verbindungen zu unserer Arbeit.
Um die Antworten etwas zu Gliedern haben wir Spiele Reihen als eine Antwort gesehen.
Zudem haben wir Witz antwoerten wie Candy Crush oder Tetris nicht zur kenntnis genommen.
Die absolute Top-antwort war _The Witcher 3: Wild Hunt_ mit 14 Pukten.
Die zweit meisste Antwort war die _Mass Effect_-Reihe (ohne _Mass Effect Andromeda_) mit 5 Punkten.
_Half-Life 2_ und _The last of us_ Teilen sich den dritten Platz mit 4 Punkten.
Danach gibt es sehr viele Antworten mit 3 Punkten wie _Life is Strange_, _Metal Gear Solid_-Reihe, _Day of the Tentacle_ und die _Untcharted_-Reihe.
Da wir die Entwicklung untersuchen haben wir versucht die Spiele zu gliedern in die Jahre in der sie erscheinen sind.
Wir habe sie nach Jahrzehnte sortiert und sehr erstaunt gemerkt das die meissten der gennanten Spiele in diesem Jahrzehnt erschienen sind.
Das heisst die meissten Spiele die in unserer Umfrage gennant wurden sind nach 2010 entwickelt worden.
Insgesamt wurden 19 Spiele aus den Jahren 2010-2018 genannt.
Von 2000-2009 waren es 16 genannte Spiele, von 1990-1999 sechs Spiele und von 1980-1989 waren es noch zwei Spiele.
Als nächstes Sortierten wir sie nach Genre.
Da teilen sich die Adventures und die Rollenspiele die selbe anzahl an erwähnungen, 15 Adventures und 15 Rollenspiele wurden genannt.
Dazu kammen noch drei Shooter swowie drei Jump'n'Run Spiele und zwei Strategie Spiele.

[cols="20,20,50,>10",options="header"]
.Auswertung der genannten Spiele
|===
| Erschienen   | Genre | Titel | Punkte
|1980 -- 1989  | Adventure | Hitchhikers Guide to the Galaxy   | 2
|              | Jump & Run | Prince of Persia                 | 1
|1990 -- 1999  | RPG       | Vampires the Masquerade | 1
|             | Adventure | Metal Gear Solid        | 3
|             |           | Day of the Tentacle     | 3
|             |           | Zelda: Ocarina of Time  | 2
|             |           | Myst                    | 1
|             | RTS       | Dugeon Keeper           | 1
|2000 -- 2009  | Jump & Run | Rattchet & Clank       | 3
|             | Adventure  | Assassins Creed        | 1
|             |            | Syberia                | 1
|             |            | Okami HD               | 1
|             |            | Portal                 | 1
|             | RPG        | Star Wars: Knights of the old Republic | 3
|             |            | Fallout                | 1
|             | Shooter    | Half-Life 2            | 4
|             |            | Call of Duty           | 5
|             |            | Bioshock               | 2
|             | RTS        | Warcraft 3             | 1
|             | RPG (MP)   | World of Warcraft      | 3
|
2010 -- 2017 | Adventure | The last of us          | 4
|             |           | Life is Strange         | 3
|             |           | Uncharted               | 3
|             |           | Beyond: 2 Souls         | 2
|             |           | Heavy Rain              | 2
|             |           | To The Moon             | 2
|             |           | What Remains of Edith Finch| 2
|             |           | Alan Wake               | 1
|             |           | The Walking Dead        | 1
|             |           | Yakuza 5                | 1
|             | RPG       | The Witcher 3           | 14
|             |           | Horizon Zero Dawn       | 2
|             |           | Mass Effect             | 2
|             |           | Skyrim                  | 2
|             |           | Dark Souls              | 1
|             |           | Divinity: Original Sin  | 1
|             |           | The binding of Isaac    | 1
|             |           | Undertale               | 1
|             | Simulation | Rimworld               | 1
|             | Action    | GTA V                   | 2
|             |           | Farcry 4                | 1
|             | Jump & Run | Ori and the blind Forrest | 1
|===
