= Einleitung

Games gibt es wie Sand am Meer und wie auch dort können Muscheln, die Perlen enthalten, gefunden werden.
Unter Perlen verstehen wir den Inhalt eines Games, wovon ein grosser Teil eine gute Story ist.
Doch will man heute überhaupt noch eine fesselnde Geschichte durchleben oder doch lieber Online mit anderen Spielern der Welt zocken?
In der Gaming-Industrie, wird unserer Meinung nach, der Online-Hype immer mehr gefördert und in den Vordergrund geschoben.
So auch das 2013 erschienene Spiel Grand Theft Auto V , eines der erfolgreichsten Spiele überhaupt.
Heute hat bestimmt jeder die Story durch, weshalb die Macher immer weiter am Online Modus arbeiten mussten und sich neue Features einfallen liessen um das Spiel weiter voran zu treiben.
Sie gaben den Spielern selbst die Möglichkeit durch Modifikationen, die man im Internet herunterladen konnte, das eigene Spielgefühl zu verändern.
Durch ihre Bemühungen lebt das Spiel fast fünf Jahre später immer noch und das nur dank dem Online Modus.
Die Gaming-Industrie macht einen spürbaren Wandel durch. So werden Einzelspieler-Kampagnen kürzer und die Story weniger stark gewichtet.
Was heute zählt, ist die Grafik und die Online Funktionen. Während ältere Gamer dies bedauern, sind viele der Jungen umso glücklicher.
Doch kann dies von uns wirklich so verallgemeinert werden? In dieser Berufsmaturitätsarbeit soll unter anderem dieser Frage und dem genannten Wandel nachgegangen werden.

<<<<<<< HEAD
stem:[\cos (2\theta) = \cos^2 \theta - \sin^2 \theta]
=======
>>>>>>> 0ceb02c038fa227c943d773099c602d994620695
