= Fragestellung & Hypothese

Fragen über Fragen, die nach Antworten suchen.
Wohin entwickelt sich die Gaming-Industrie?
Wollen die Konsumenten Lieber eine packende Story oder einen tollen Online-Modus mit vielen Funktionen?
Hat dieser Wunsch nach Neuem mit dem Alter der Spieler zu tun oder kann man das nicht so verallgemeinern?
Wenn dem so ist, wann hat dann diese neue Spiele-Ära begonnen und welche Altersgruppe ist am zufriedensten?
All das versuchen wir in dieser Arbeit zu untersuchen und zu beantworten.
Dafür definierten wir eine Leitfrage und legten uns auf einen Zeitraum fest, da es sonst zu viel geworden wäre.
In unserem Fall lautet diese: Hat sich die Wichtigkeit der Story-Line der Games in den letzten 20 Jahren verändert?
Wir denken, dass vor allem die jüngeren Spieler lieber online mit ihren Freunden spielen und die älteren eher eine gute Geschichte geniessen möchten.
Was den Wandel in der Branche angeht vermuten wir, dass die Industrie eher mit dem Online Trend mitfährt, da immer mehr Games neben der Story einen Online-Modus haben oder sogar nur Online zu spielen sind.
Zu behaupten die Story sei gänzlich unwichtig geworden, würden wir nicht wagen, da dies absolut nicht der Fall ist.
Dennoch spüren wir diese Bewegung in eine neue Richtung.
Wir können verstehen, dass der Online Trend für die Spielemacher lukrativ ist, da man dort gut sogenannte Micro-Transactions einbringen kann, die immer weiter für Einnahmen sorgen.
Ebenfalls ist der technische Fortschritt ein Faktor, den man nicht ausser Acht lassen sollte.
Dieser eröffnet natürlich viele neue Features, die vor 20 Jahren, als Online zu spielen noch nicht mal eine Idee war, noch nicht möglich waren.
Nicht minder ist aber die Trauer bei uns, wenn ein Spiel, das man schon lange erwartet, plötzlich nur eine kurze Story hat und einem nur noch der Online Modus bleibt.
Wir sind überzeugt, dass wir nicht die Einzigen sind, die so denken, viele aber auch anderer Meinung sind.
Wir können aber nicht einfach nur Behauptungen in den Raum stellen und den Stempel darunter machen, weswegen wir uns Methoden erarbeiteten um unsere These zu bestätigen oder auch zu wiederlegen.
Wir entschieden uns zu diesem Zweck neben der Literaturrecherche auch eine Umfrage zu machen.
Das Ziel dieser Umfrage war es, mindestens 50 Gamer von verschiedenen Altersgruppen zu fragen, was sie von unserer These halten und was ihrer Meinung nach wichtiger ist.
Wir stellten also unsere Fragen zusammen und erstellten eine online Umfrage, die wir sogleich an Freunde und Bekannte sandten.
