Wandel der Story-Relevanz in Videospielen
=========================================

Tobias Fischer <tobias@invisible.ch>
Tenzin Bhusethang <tbd>


:doctype: book
:icons:
:max-width: 45em
:toc: macro
:toc-title: Inhaltsverzeichnis
:appendix-caption: Anhang
:table-caption: Tabelle

:pdf-stylesdir: theme
:pdf-style: pdf.yaml
:figure-caption: Abbildung

:math:
:stem: latexmath

toc::[]

:numbered:

// Push titles down one level
:leveloffset: 1

include::Abstract.adoc[]

include::einleitung.adoc[]

include::Story in Videospielen.adoc[]

include::Die Entstehung von Story in Videogames.adoc[]

include::Auswertung der Umfrage.adoc[]

include::Schlusswort.adoc[]

:numbered!:

include::Literaturverzeichnis.adoc[]

include::Danksagung.adoc[]

include::umfrage.adoc[]

include::auswertung.adoc[]



// Return to normal title levels
:leveloffset: 0


[glossary]
== Glossar

Cutscenes::	Zwischensequenzen, in denen Gameplay durch Film ersetzt wird und die Story fortgeführt wird.

Features:: 	Zusätzliche Funktionen.

Gameplay::	Aktionen des Spie&#173;lers, wie Steuerung, Kämpfe und Entscheidungen

Gamer::	Der Spie&#173;ler/ der Konsument

Games::	die Videospiele

Jump &Run:: Spiele in denen man Parcours mit Sprüngen meistert. (Super Mario)

Micro-Transactions::	Möglichkeit im Spiel für echtes Geld Dinge zu erwerben

Multiplayer:: Man spielt online oder lokal mit anderen Leuten.

Online Funktion:: 	Die Möglichkeit mit andern Spie&#173;lern im Internet zu spielen.

Online-Hype::	Die Freude an der Möglichkeit mit andern Spie&#173;lern zu interagieren

RPG::	Role-Playing Games sind Spiele in denen man nicht nur die Story spielt, sondern wirklich in die Rolle eintauchen muss (z.B. durch das Treffen von Entscheidungen).

Singleplayer::	Man spielt die Story alleine und offline. Der Fokus liegt auf der Story

Story-Line (Story)::	Die Ge&#173;schich&#173;te, die erzählt wird.

Storytelling::	Die Art wie die Ge&#173;schich&#173;te erzählt wird, zum Beispiel mit Büchern.

Trend:: Beobachtbare Entwicklung in Vorlieben der Konsumenten.
