Wandel der Story-Relevanz in Video&#173;spielen
=========================================

Tobias Fischer <tobias@invisible.ch>
Tenzin Bhusethang <tbd>


:doctype: book
:icons:
:max-width: 45em
:toc: macro
:toc-title: Inhaltsverzeichnis
:appendix-caption: Anhang
:table-caption: Tabelle

:pdf-stylesdir: theme
:pdf-style: pdf.yaml
:figure-caption: Abbildung

:math:
:stem: latexmath

toc::[]

:numbered:

// Push titles down one level
:leveloffset: 1

include::Abstract.adoc[]

include::einleitung.adoc[]

include::Story in Videospielen.adoc[]

include::Die Entstehung von Story in Videogames.adoc[]

include::Auswertung der Umfrage.adoc[]

include::Schlusswort.adoc[]

:numbered!:

include::Literaturverzeichnis.adoc[]

include::Danksagung.adoc[]

include::umfrage.adoc[]

include::auswertung.adoc[]



// Return to normal title levels
:leveloffset: 0


[glossary]
== Glossar

Singleplayer:: Man spielt die Story alleine und offline, Fokus auf Story

Multiplayer:: Man spielt online oder lokal mit anderen Leuten, meist keine Story

Micro-Transactions:: Möglichkeit im Spiel für echtes Geld Dinge zu erwerben

Cutscenes::	Zwischensequenzen, in denen Gameplay durch Film ersetzt wird

Gameplay:: Alles was der Spieler macht (steuern, kämpfen, entscheiden etc.)

RPG::	Role-Playing Games sind spiele in denen man nicht nur die Story spielt, sondern wirklich in die Rolle eintauchen muss (z.B. durch da treffen von Entscheidungen).

Story-Line:: Die Ge&#173;schich&#173;te, die Erzählt wird.

Jump &Run::	Spiele in denen man Parcours mit Sprüngen meistert. (Super Mario)

Plot:: Die Handlung
