= Motivation

Als wir erfahren haben das wir eine Maturarbeit schreiben mussten, war für uns klar wir wollten etwas tun was uns Spass macht.
Tobias hatte die Idee, etwas mit Gaming zu machen.
Da wir beide leidenschaftliche Gamer sind, fanden wir die Idee gut und machten uns auf die Suche nach einem geeigneten Thema.
Wir beide lieben Role-playing Games (RPG) und versuchten deshalb, diese in unser Thema einzubauen.
RPG's sind in den 80er und 90er Jahren gross geworden und prägten die Gaming Industrie.
Wir sind beide Ende der 90er Jahre geboren und haben uns erst in unserer frühen Jugend mit Games befasst.
Da wir und deshalb viel Gaming Geschichte verpasst haben, ist uns die Idee gekommen, die Veränderung von RPGs im Laufe der Zeit zu analysieren.
Wir waren beide zufrieden mit unserem Thema, merkten aber schnell, dass es viele Schwierigkeiten geben würde unser Thema so umzusetzen, aber wir wollten unser Thema weiter behandeln.
Uns wurde klar, dass es nicht Funktionieren würde und machten uns auf die Suche nach einem neuen Thema.
Wir hatten mehrere Ideen welche auch im Bereich Gaming waren.
Wir wollten zum Beispiel etwas über E-Sports machen, jedoch waren unsere Meinung zu unterschiedlich und wir hätten keine Arbeit darüber schreiben können.
Eine Idee war es, die Produktion von Videogames zu untersuchen. Wir haben uns nun entschieden, die Story von Videogames untersuchen , indem wir verschiedene RPGs der letzten 10 Jahre anschauen.
Schlussendlich haben wir zusammen mit unserer Betreuungsperson die Idee gehabt, die Meinung von Konsumenten zur Storyline in Games herauszufinden.
Gleichzeitig wollen wir darlegen wie Storytelling in Games entstanden ist und was genau die Storyline in Games ist.
Von Anfang an wollten wir ein Interview oder eine Umfrage machen um unsere Arbeit zu unterstützen und dieses Thema ermöglichte dies.
