= Reflexion von Tobias Fischer

== Prozess

Zeit Menagement eines der grössten Probleme die wir hatten.
Ich persondlich bin schon immer ein Chaot und nicht gut im Zeit Menagement.
Damit ich die Arbeit dennoch fertig machen kann, ohne in der letzten Woche die Nächte durchzuarbeiten, bat ich meine Mutter um Hilfe.
Sie erstellte mir für die letzten 3 Wochen vor abgabe einen Strikten Zeitplan den ich einhalten musste.
Anfangs hat es sehr gut Funktioniert.
Dennoch musste ich an zwi Wochenenden sehr viel schreiben und korrigieren.
Bessonders das letzte Wochenende vor der Abgabe war sehr anstrengend.
Ich habe an beiden Tagen über sechs Stunden an der Arbeit gearbeitet und auch mein Vater hat mir an diesen Tagen geholfen.
Er korrigierte meine Rechtschreibungsfehler und gab mir Tips was ich noch ändern oder anpassen könnte.
Da wir meherer Male unser Thema wechselten und nie wirklich sicher waren was wir genau tun sollten haben wir nie einen Definitiven Zeitplan erstellt.
Für mich Persöndlich war die Rechtschreibung auch ein sehr grosses Problem.
Bei den Korrekturen brauchte ich sehr viel Hilfe.
Dazu kam das ich vor Weinachten eine Operation am Steissbein hatte was mich daran hinderte an der Arbeit konzentriert zu arbeiten.
Durch die Schmerzen konnte ich in den Weinachtsferien nicht an der Arbeit schreiben.
Dies war ein Problem da der Abgabe Termin immer näher rückte.

== Arbeit

Ich bin mit unserem End Ergebnis zufrieden.
Mit einer besseren Planung und ohne rückschläge in Themenwahl oder Gesundheitlichen Gründen bin ich mir sicher hätten wir mehr aus der Arbeit herausholen können.
Dennoch bin ich zufrienden mit der Arbeit.
Ich hatte auch Spass die Arbeit zu schreiben auch wenn es sehr lange dauerte.
Bessonders Spass machten mir die Diskusionen mit meinem Vater.
Als ich merkte das ich in einen guten Schreibfluss kam, wurde ich noch Motivierter die Arbeit zu schreiben.
Mir freute sehr das die Zitate in der Arbeit meiner Meinung nach so gut aussehen.

== Zusammenarbeit

Hier muss ich sagen haperte es oft in unserem Team.
Unser Zeitmenagement war sehr schlecht und auch die Komunikation machte Probleme.
Anfangs wussten wir gar nicht was wir eigentlich machen sollten und machten dann nichts dagegen.
Leider hat Tenzin das Dossier welches wir von der Schule bekommen haben warscheindlich nicht ein einzigesmal durchgelesen.
Dazu kam das Tenzin für die Einleitung und das Abstract verantwortlich war.
Als ich die Einleitung und das Abstract anschaute wurde mir klar das ich fast alles nochmal umschreiben muss.
Auch die anderen Teile der Arbeit waren sehr umgangssprachlich geschrieben.
Ich musste extrem viel der Arbeit umschreiben oder neu schreiben, was dazu führe das ich am letzten Wochenende so lange daran arbeitete.
Leider muss ich sagen das ich ca. 80% der Arbeit geschrieben habe, da ich so viel ändern musste.
