= Schwierigkeiten

In unserem Team gab es einige Schwierigkeiten.
Am Anfang hatten wir Mühe eine Thematik zu finden die uns beide interessierte und dann davon noch eine Ableitung zum Thema Wandel.
Die erste Idee wurde schon während der Projektwoche verworfen.
Die Zweite war ein Missverständnis, da es zwischen uns Kommunikationsfehler gab.
Wir hatten die Vereinbarung unterzeichnet und begannen zu arbeiten, doch bei der ersten Zwischenbesprechung wurde klar, dass wir die Lehrperson falsch verstanden hatten.
Wir konnten unseren ganzen bisherigen Fortschritt wieder verwerfen und mussten eine neue Vereinbarung aufsetzen und unterzeichnen.
Wir hatten nun zwar eine endgültige Vereinbarung, doch kaum mehr als 6 Wochen Zeit die ganze Arbeit zu verfassen.
Wir mussten uns also beeilen und die Umfrage möglichst schnell in Umlauf bringen.
Weil aber Tobias zu dieser Zeit operiert wurde verloren wir nochmals Zeit, in der wir gemeinsam arbeiten konnten.
Nun lief eine Weile alles gut, wir kamen gut voran doch als Tenzins PC abstürzte, verloren wir einen kleine Teil der Arbeit, die wir zum Glück schnell wieder neu verfasst hatten.
