= Story in Videogames

== Geschichten gab es schon immer

Wieso gibt es überhaupt eine Geschichte in Videogames?
Nun Menschen haben schon immer Gefallen an interessanten Geschichten gezeigt.
Menschen erzählen sich seit jeher Geschichten. In Theater, Kino, Gedichte, Literatur, Lieder und nun auch in Games.
Bereits die Höhlenmenschen zeichneten ihre Erlebnisse an die Wände.
Im Mittelalter hat man Theaterstücke aufgeführt und Gedichte geschrieben.
Es ist der Inhalt, der den Menschen packt und interessiert.
Schon als Kinder liebten wir es Geschichten zu hören.

Im Buch "The Seven Basic Plots: Why We Tell Stories" von (<<Booker2004>>) schreibt er, es gibt sieben arten wie wir eine Handlung einer Geschichte erzählen.

Das Monster überwinden:: Der Protagonist versucht eine meist böse Macht die ihn bedroht zu überwinden.

Von Lumpen zu Reichtum:: Der arme Protagonist bekommt Sachen wie Stärke, Geld, Macht nur um sie wieder zu verlieren um sie dann zurück zu bekommen nachdem er als Mensch gewachsen ist.

Die Aufgabe:: Der Protagonist und sein Gefolge versuchen ein wichtiges Objekt zu finden oder einen speziellen Ort zu erreichen. Auf der Reise müssen sie viele Gefahren und versuchungen zu überwinden.

Reise und Rückkehr:: Der Protagonist geht in ein fremdes Land, überwindet die Gefahren die auf ihn lauern und kehrt dann mit erfahrung zurück.

Komödie:: Leicht und Humorvoller Charakter mit einem glücklichen oder lustigem Ende.

Tragödie:: Der Protagonist ist ein Held mit einer offensichtlier Charakterschwäche oder einem grossen Fehler was am ende zu seinem untergang führt.

Wiedergeburt:: Im Lauf der Geschichte zwingt ein Erignis den Protagonist seine Art zu ändern, was ihn oft zu einem besseren Menschen macht.

Auch in Videospielen sind diese arten von Geschichten oft vertreten.
Dabei tauchen am häufigsten das überwinden von Monstern auf.
Auch die Aufgabe wird oft behandelt.
Tragödien sind viel in neuen Adventures zu finden wie zum Beispiel _The walking Dead_


== Der Anfang von Geschichten in Videospielen

Games haben vielleicht mit Geschicklichkeit und Denkspielen angefangen jedoch sind Adventures sehr schnell dazu gekommen.
Das erste bekannte Adventure ist 1975 erscheinen es ist ein reines Textadventure und heisst _Adventure_.
Später kamen weiter Textadventures, besonders bekannt war die _Zork_-Reihe von der Firma Inform.
In den 80er Jahren wurden dann Textadventures von Grafik-Adventures abgelöst.
Mit den Grafik und Textadventures hat man dann angefangen in Games Geschichten zu erzählen und bald danach sind Role-Playing Games dazugekommen.

== Linearität

Im Theater oder in der Literatur wird eine Geschichte linear erzählt.
Früher im greichischen Theater gab es eine Einheit von Raum und Zeit, dass heisst wenn das Theater zwei Stunden lang dauert, so dauert auch die Geschichte die erzählt wird zwei Stunden lang, später hat man mit Szenenwechsel Zeitsprünge vornehmen können.
In Literatur, Theater und Film kann man mehrere Zeitebenen parallel erzählen.
Dennoch wird die Geschichte vom Erzähler in einer vorgegeben Reihenfolge erzählt.
In einem Spiel kann dies auch so geschehen, zusätzlich besteht die Möglichkeit dem Spieler die Steuerung des Geschichtsflusses zu ermöglichen.
Man verändert die Geschichte je nach dem was man in dem Spiel macht.
Zudem gibt es Spiele deren Geschichte durch die Handlungen des Spielers beinflusst werden oder erst durch diese entstehen.
Für Storyteller ist es viel anspruchsvoller eine Non-Lineare Geschichte zu schreiben in dem sie dem Spieler die Entscheidung lassen was und wann er es erlebt.

Es gibt auch Techniken, den Fluss einer dynamischen Geschichte so zu steuern, dass der Spieler den Hauptstrang so erlebt, wie es der Autor vorgesehen hat.
Der Spieler muss zum Beispiel einen bestimmten Ort erreichen um in der Story weiter zu kommen.
Es gibt auch Games die keine Story von einem Autor haben, sondern deren Geschichte automatisch, aufgrund von Aktionen und Reaktionen des Spielers generiert wird.

== Der Einfluss von Film

Durch den technischen Fortschritt, vorallem im Bereich der Grafik, können Spiele immer neher an das visuelle Aussehen von Filmen kommen.
Wie (Pöhnert2005) schreibt, wurden mit den immer besser werdender Technischen Gegebenheiten, immer längere und bessere Spielfilmartige Sequenzen möglich.
Diese Sequenzen nennt man auch 'Cutscenes', welche zur Belohnung des Spielers und auch der Erzählung der Geschichte beitragen.

Heute, 12 Jahre später sind die technischen Möglichkeiten so weiterentwickelt, dass es möglich ist, quasi realistische Bilder im eigentlichem Spiel zu haben.
Zum Beispiel wird mit sogenantem "Motion capturing" das Aussehen und die Bewegung von Schauspielern aufgenommen.
Die sich daraus ergebenen Daten machen es möglich, das sich eine Figur im Spiel natürlich bewegt, auch wenn die jeweilige Aktion oder Handlung nicht vorgegeben war.
Weil es so ändlich ist wie Film ist es interessant was Filmregisseure dazu sagen,



== Filmregisseure über Games

In einem Interview das (<<bishop2013>>) mit Steven Spielberg und George Lucas geführt hat, wird über Storytelling in Games diskutiert.

[quote]
--
"Telling a story, it’s a very complicated process," he said.
"You’re leading the audience along.
You are showing them things.
Giving them insights.
It’s a very complicated construct and very carefully put together.
If you just let everybody go in and do whatever they want then it’s not a story anymore.
It’s simply a game."
--

Wir verstehen was uns Lucas hier sagen will, jedoch sehen wir dies etwas anders.
Es ist nicht einfach nur ein Spiel sondern der Spieler selber wird zum gestallter der Geschichte und kann diese erleben wie er es für sich persönlich gerne hätte.
Der Spieler wird teilweise sogar dazu animiert die Geschichte des Spieles selber zu gestallten oder herauszufinden.
Somit gibt es sehr viele Interpretationen, auch in der Literatur oder im Film wird etwas ändliches gemacht.
Man lässt die Geschichte offen und lässt die Leser und die Betrachter spekulieren was passieren könnte.
Dadurch öffnet man eine völlig neue herangehensweise an die Geschichte und ob dies in einem Spiel oder einem Film passiert ist nicht relevant.
Zum Beispiel in der Fernseh-Serie _Game of Thrones_, nach jeder Staffel gibt es im Internet aber tausende Theorien was nun als nächstes in der Serie passieren könnte oder wie die Serie endet.
Das selbe gibt es auch in Videospielen, in _World of Warcraft_, welches eine immer weitergehende Geschichte besitzt, werden immer wieder Theorien aufgestellt was mit den Charakteren und der Spielwelt als nächstes passiert.
In _World of Warcraft_ ist die Art wie die Geschichte erzählt wird sehr speziell.
Der Spieler ist ein teil der Spielwelt und hat auch Einfluss auf diese.
Im Jahr 2017 ist das neue Erweiterungs-Paket für _World of Warcraft_ erschienen.
Die Spieler machten sich auf den Weg neue Ort zu entdecken, Stärker zu werden und neue Verbündete zu gewinnen.
Die Geschichte von _World of Warcraft_ ist eine Klassische "Monster überwinden"-Story, jedoch gibt es nicht nur einen Protagonisten sondern die Spieler müssen zusammen gegen die Monster kämpfen.
Wir sehen das so, dass dies auch eine Geschichte ist und nicht nur ein Spiel, auch wenn jeder das machen kann was er will.


George Lucas sagte auch:

[quote]
--
"Storytelling is about two things," he said.
"It’s about character and plot."
Character is what movies and television offer, he said, but it’s a concept the gaming industry is just now discovering.
"Like sports. It’s about Tebow.
It’s about, you know, Kobe.
They’re starting to realize that if they focus on the characters it makes the game much richer."

"But by its very nature there cannot be a plot in a game.
You can’t plot out a football game.
You can’t plot out feeding Christians to lions.
It’s not a plot."
--


Nun auch diese Aussage finden wir etwas fragwürdig.
Für uns kann es auch in einem Spiel eine gute Handlung haben.
Man nehme _The Witcher 3: The Wild Hunt_ als Beispiel, ein Spiel welches auf einem Roman basiert.
Jedoch sind wir uns sicher das jeder der das Spiel gespielt und das Buch gelesen hat sagen wird das in dem Spiel die Story viel besser rüber kommt als im Buch.
Die Geschichte des Spieles ist sehr vielfaltig.
Es werden viele kurze Geschichten erzählt die auch zur Hauptgeschichte beitragen.
Viele von diesen Geschichten fallen wieder in unser Schema, es gibt "Monster überwinden"-Storys, "Die Aufgabe"-Passagen und auch "Tragödien" werden erzählt.
Es gibt auch sehr gute Beispiele von Spiele die nicht auf einem Buch basieren.
Die _Mass Effect_-Reihe, welche auch klare verbindungen zu den oben erwähnten Handlungstypen aufweist.
Wir stehen dammit im Wiederspruch zur Aussage von Lucas, denn wir finden das es auch in Videospielen einen "Plot" geben kann.
