= Von "Dungons and Dragons" zu RPG's

== Dungons and Dragons

Ich denke fast jeder hat schonmal von "Dungons and Dragons" gehört.
Wir verbiden es oft mit jungen Nerds die im Keller eingeschlossen mit ihren Freunden "Dungons und Dragons" spielen.
Nun was ist den dieses omimöse "Dungons and Dragons"?
Es ist ein sogenantes Pen and Paper Rollenspiel und wie der Name schon verät spielt man es mit Papier und Stift.
Der Spieler schlüpft in eine fiktive Rolle und erlebt mit seinen mit Spielern verschidene Abenteuer.
Der Spielleiter ist wie der Erzähler in einem Buch oder Film und die Spieler verkörpern die Charaktere.
Nun anstat das vorgegeben ist wie sich die Charaktere verhalten und was sie als nächstes tun entscheiden die Spieler selber was sie als nächstes machen.
Man sieht klare zusammen hänge zu heuteigen Role-playing Games.
Wie wir bereits erklärten wird der Spieler zum Gestallter der Geschichte und erlebt die Geschichte gleichzeitig mit.

== Role-playing Games

Die Wurzeln der RPG's stammen hauptsächlich aus den oben genannten Pen and Paper Rollenspielen.
Jedoch übernimmt hier der Computer die Rolle des Spielleiter, welches natürlich Einschränkungen mit sich zieht.
Hier ist es vorgschrieben was passiert duch die Spielentwickler.
Die ersten Computer Rollenspiele entstanden mitte der 70er Jahre.
Da Universitäten die einzigen Institutionen waren welche über eingeschränkt zugängige Rechner verfügten, waren es Studenten welche die ersten Rollenspiele Entwickelten.
Speicherplatz war zu dieser Zeit sehr wertvoll, deshalb hatten Universitäten eine Strenge Löschplitik.
Das heisst das fast alle zu dieser Zeit entwickelten Rollenspiele gelöscht wurden.
Das älteste noch erhaltene Rollenspiel heist "dnd" und wurde 1974 an der Universität Illinois entwickelt.
Heute gibt es diese Rollenspiele immer noch, auch wenn das Genre nicht mehr so gross ist wie vor ein paar Jahren.
Ein gutes Beispiel für ein Videospiel welches noch sehr klare Verwantschaften mit "Dungons and Dragons" hat ist "Divinity: Orignial sin 2", welches im Herbst 2017 erscheien ist.
Im Spiel gibt es sogar eine Funktion ein Pen and Paper Spiel mit seinen Freunden zu spielen.
Der Stift und das Papier ist zwar nicht vorhanden aber dennoch ist es fast identisch zu dem Orginal.
Das gute ist man muss sich die Abenteuer nicht vorstellen, sondern man erlebt sie am Bildschirm mit.
